/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ProyectoProgram;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class vBorrarDirectorio extends javax.swing.JFrame {

    /**
     * Creates new form vBorrarDirectorio
     */
    public vBorrarDirectorio() {
        initComponents();
        this.setLocationRelativeTo(null);
        lNombre.setVisible(false);
        lUbicacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bBorrar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfUbicacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        bOK = new javax.swing.JButton();
        lNombre = new javax.swing.JLabel();
        lUbicacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BORRAR DIRECTORIO");

        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        bBorrar.setBackground(new java.awt.Color(102, 255, 51));
        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bSalir.setBackground(new java.awt.Color(255, 153, 153));
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Ubicacion");

        tfUbicacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUbicacionFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("ID");

        tfID.setEditable(false);
        tfID.setBackground(new java.awt.Color(0, 0, 0));
        tfID.setForeground(new java.awt.Color(255, 255, 255));
        tfID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        bOK.setBackground(new java.awt.Color(255, 153, 0));
        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        lNombre.setForeground(new java.awt.Color(255, 0, 0));
        lNombre.setText("*Nombre incorrecto");

        lUbicacion.setForeground(new java.awt.Color(255, 0, 0));
        lUbicacion.setText("*Ubicacion incorrecta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfUbicacion)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                            .addComponent(bSalir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lNombre))
                            .addComponent(lUbicacion)
                            .addComponent(bOK)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(bBorrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfID)
                        .addGap(108, 108, 108)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lUbicacion))
                            .addComponent(lNombre))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOK))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar)
                    .addComponent(bSalir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        ProyectoProgram.cerrarVentanaBorrarDirectorio();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        try {
            if(ProyectoProgram.validarNombre(tfNombre.getText())&& ProyectoProgram.validarNombre(tfNombre.getText())  && ProyectoProgram.validarUbicacion(tfUbicacion.getText())&& ProyectoProgram.validarUbicacion(tfUbicacion.getText()) && ProyectoProgram.directorioEncontrado(tfNombre.getText(),tfUbicacion.getText()) && !tfNombre.getText().isEmpty() && !tfUbicacion.getText().isEmpty()){
                ProyectoProgram.borrarDirectorio(tfNombre.getText(),tfUbicacion.getText());
                JOptionPane.showMessageDialog(this, "Directorio borrado de la base de datos");
                ProyectoProgram.cerrarVentanaBorrarDirectorio();
            }else if(!ProyectoProgram.directorioEncontrado(tfNombre.getText(),tfUbicacion.getText())){
                JOptionPane.showMessageDialog(this, "Este directorio no existe en la base de datos");    
            }else if(!ProyectoProgram.validarNombre(tfNombre.getText())){
                JOptionPane.showMessageDialog(this, "Este nombre es incorrecto");    
            }else if(!ProyectoProgram.validarUbicacion(tfUbicacion.getText())){
                JOptionPane.showMessageDialog(this, "Este nombre es incorrecto");    
            }else{
                JOptionPane.showMessageDialog(this, "No pueden estar vacio s el nombre y la ubicacion");
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }    
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        try {
            if(ProyectoProgram.directorioEncontrado(tfNombre.getText(),tfUbicacion.getText()) && !tfNombre.getText().isEmpty() && !tfUbicacion.getText().isEmpty()){
                try {
                    int id = ProyectoProgram.buscarIdDirectorio(tfNombre.getText(), tfUbicacion.getText());
                    String ids = Integer.toString(id);
                    tfID.setText(ids);
                } catch (Exception e) {
                    System.out.println("Error " + e.getMessage());
                }
            }else if(!ProyectoProgram.directorioEncontrado(tfNombre.getText(),tfUbicacion.getText())){
                JOptionPane.showMessageDialog(this, "Este directorio no existe");    
            }else{
                JOptionPane.showMessageDialog(this, "No pueden estar vacio s el nombre y la ubicacion");
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }    
    }//GEN-LAST:event_bOKActionPerformed

    private void tfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusLost
         if(!ProyectoProgram.validarNombre(tfNombre.getText())){
            lNombre.setVisible(true);
        }else{
             lNombre.setVisible(false);
         }
    }//GEN-LAST:event_tfNombreFocusLost

    private void tfUbicacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUbicacionFocusLost
        if(!ProyectoProgram.validarUbicacion(tfUbicacion.getText())){
            lUbicacion.setVisible(true);
        }else{
            lUbicacion.setVisible(false);
        }
    }//GEN-LAST:event_tfUbicacionFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vBorrarDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vBorrarDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vBorrarDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vBorrarDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vBorrarDirectorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bOK;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lUbicacion;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfUbicacion;
    // End of variables declaration//GEN-END:variables
}
