/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ProyectoProgram;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class vModificarFichero extends javax.swing.JFrame {

    /**
     * Creates new form vDirectorio
     */
    public vModificarFichero() {
        initComponents();
        this.setLocationRelativeTo(null);
        lNombre.setVisible(false);
        lExtension.setVisible(false);
        lNombre2.setVisible(false);
        lExtension2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfExtension = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfHora = new javax.swing.JTextField();
        bSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfNuevoNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNuevaExtension = new javax.swing.JTextField();
        tfID = new javax.swing.JTextField();
        bVerId = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lExtension = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lNombre2 = new javax.swing.JLabel();
        lExtension2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bModificar.setBackground(new java.awt.Color(102, 255, 0));
        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFICAR FICHERO");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Extension:");

        tfExtension.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfExtensionFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Fecha:");

        tfFecha.setEditable(false);
        tfFecha.setBackground(new java.awt.Color(0, 0, 0));
        tfFecha.setForeground(new java.awt.Color(255, 255, 255));
        tfFecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setText("Hora:");

        tfHora.setEditable(false);
        tfHora.setBackground(new java.awt.Color(0, 0, 0));
        tfHora.setForeground(new java.awt.Color(255, 255, 255));
        tfHora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        bSalir.setBackground(new java.awt.Color(255, 153, 153));
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Nuevo nombre:");

        tfNuevoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNuevoNombreFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setText("Nueva Extension:");

        tfNuevaExtension.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNuevaExtensionFocusLost(evt);
            }
        });
        tfNuevaExtension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevaExtensionActionPerformed(evt);
            }
        });

        tfID.setEditable(false);
        tfID.setBackground(new java.awt.Color(0, 0, 0));
        tfID.setForeground(new java.awt.Color(255, 255, 255));
        tfID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        bVerId.setBackground(new java.awt.Color(255, 153, 0));
        bVerId.setText("Ver");
        bVerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerIdActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText("ID");

        lExtension.setForeground(new java.awt.Color(255, 0, 0));
        lExtension.setText("*Extension incorrecta");

        lNombre.setForeground(new java.awt.Color(255, 0, 0));
        lNombre.setText("*Nombre incorrecto");

        lNombre2.setForeground(new java.awt.Color(255, 0, 0));
        lNombre2.setText("*Nombre incorrecto");

        lExtension2.setForeground(new java.awt.Color(255, 0, 0));
        lExtension2.setText("*Extension incorrecta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNombre2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lExtension))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVerId))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNuevaExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lExtension2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVerId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lExtension))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNuevaExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lExtension2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalir)
                    .addComponent(bModificar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        try {
            if(!ProyectoProgram.ficheroEncontrado(tfNuevoNombre.getText(), tfNuevaExtension.getText())&& ProyectoProgram.validarExtension(tfExtension.getText())&& ProyectoProgram.validarNombre(tfNombre.getText()) && !tfNombre.getText().isEmpty() && !tfExtension.getText().isEmpty() && !tfNuevoNombre.getText().isEmpty() && !tfNuevaExtension.getText().isEmpty()){
                ProyectoProgram.modificarDatosFichero(tfNombre.getText(), tfExtension.getText(),tfNuevoNombre.getText(), tfNuevaExtension.getText());
                JOptionPane.showMessageDialog(this,"Fichero modificado correctamente");
                tfNombre.setText("");
                tfExtension.setText("");
                tfNuevoNombre.setText("");
                tfNuevaExtension.setText("");
            }else if(ProyectoProgram.ficheroEncontrado(tfNuevoNombre.getText(), tfNuevaExtension.getText())){
                JOptionPane.showMessageDialog(this, "Ya existe "+tfNuevoNombre.getText() + " con esta extenstion: "+ tfNuevaExtension.getText());
            }else if(!ProyectoProgram.validarExtension(tfExtension.getText())){
                JOptionPane.showMessageDialog(this, "Extension mal introducida");
            }else if(!ProyectoProgram.validarNombre(tfNombre.getText())){
                JOptionPane.showMessageDialog(this, "Nombre mal introducido");
            }else{
                JOptionPane.showMessageDialog(this, "No puede estar ningun campo vacio");
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        ProyectoProgram.cerrarVentanaModificarFichero();
    }//GEN-LAST:event_bSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LocalDate localDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-yy");
        String fecha = localDate.format(formatter);
        
        LocalTime localTime = LocalTime.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");
        String hora = localTime.format(dtf);
        
        tfFecha.setText(fecha);
        tfHora.setText(hora);
    }//GEN-LAST:event_formWindowOpened

    private void tfNuevaExtensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevaExtensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNuevaExtensionActionPerformed

    private void bVerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerIdActionPerformed
        if(!tfNombre.getText().isEmpty() && !tfExtension.getText().isEmpty()){
            try {
                int id = ProyectoProgram.buscarIdFichero(tfNombre.getText(), tfExtension.getText());
                String ids = Integer.toString(id);
                tfID.setText(ids);
            } catch (Exception e) {
                System.out.println("Error " + e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "No pueden estar vacios el nombre y la extension");
        }
    }//GEN-LAST:event_bVerIdActionPerformed

    private void tfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusLost
        if(!ProyectoProgram.validarNombre(tfNombre.getText())){
            lNombre.setVisible(true);
        }else{
            lNombre.setVisible(false);
        }
    }//GEN-LAST:event_tfNombreFocusLost

    private void tfExtensionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfExtensionFocusLost
        if(!ProyectoProgram.validarExtension(tfExtension.getText())){
            lExtension.setVisible(true);
        }else{
            lExtension.setVisible(false);
        }
    }//GEN-LAST:event_tfExtensionFocusLost

    private void tfNuevoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNuevoNombreFocusLost
        if(!ProyectoProgram.validarNombre(tfNuevoNombre.getText())){
            lNombre2.setVisible(true);
        }else{
            lNombre2.setVisible(false);
        }
    }//GEN-LAST:event_tfNuevoNombreFocusLost

    private void tfNuevaExtensionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNuevaExtensionFocusLost
        if(!ProyectoProgram.validarExtension(tfNuevaExtension.getText())){
            lExtension2.setVisible(true);
        }else{
            lExtension2.setVisible(false);
        }
    }//GEN-LAST:event_tfNuevaExtensionFocusLost
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vDirectorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vDirectorio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bVerId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lExtension;
    private javax.swing.JLabel lExtension2;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNombre2;
    private javax.swing.JTextField tfExtension;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfHora;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNuevaExtension;
    private javax.swing.JTextField tfNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
